version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_ACCOUNT=matti
      - POSTGRES_PASSWORD=secret34898525
      - POSTGRES_DATABASE=videogames
      - POSTGRES_SYNCHRONIZE=true
      - POSTGRES_ENTITIES="src/entities/**/*.ts"
    ports:
      - 4002:4002

  postgres:
    image: postgres:15.1
    environment:
      - POSTGRES_USER=matti
      - POSTGRES_PASSWORD=secret34898525
      - POSTGRES_DB=videogames
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 4001:5432
