version: '3.1'

services:
  codrr:
    image: postgres:15.1
    container_name: videogames3  
    restart: always
    environment:
       POSTGRES_DB: videogames3
       POSTGRES_USER: matti
       POSTGRES_PASSWORD: secret1234
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432