version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile

    environment:
      - POSTGRES_HOST=dpg-cie3lj98g3n4p2rfp95g-a.oregon-postgres.render.com
      - POSTGRES_PORT=5432
      - POSTGRES_ACCOUNT=matti909
      - POSTGRES_PASSWORD=O3J11bvzUmoFVyR88XRFmi2Itl8COGSV
      - POSTGRES_DATABASE=dbgames_93fg
      - POSTGRES_SYNCHRONIZE=true
      - POSTGRES_ENTITIES="src/entities/**/*.ts"
    ports:
      - 4002:4002
      - 5432:5432
