version: '3.1'

services:
  db:
    image: postgres:15.1
    container_name: dbgames
    restart: always
    environment:
      POSTGRES_DB: videogames
      POSTGRES_USER: matti
      POSTGRES_PASSWORD: secret34898525
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 4000:5432
