version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile

    environment:
      - POSTGRES_HOST=
      - POSTGRES_PORT=
      - POSTGRES_ACCOUNT=
      - POSTGRES_PASSWORD=
      - POSTGRES_DATABASE=
      - POSTGRES_SYNCHRONIZE=true
      - POSTGRES_ENTITIES="src/entities/**/*.ts"
    ports:
      - 4002:4002
      - 5432:5432

  postgres:
    image: postgres:15.1
    environment:
      - POSTGRES_USER=
      - POSTGRES_PASSWORD=
      - POSTGRES_DB=
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - 4001:5432
      - 5432:5432
